### ISSUE TITLE
Invalid JSON string exception on SignInSilentlyAsync/SignInAsync?

### ISSUE THREAD

**Issue by Murtaya** [microsoft/xbox-live-api#512] opened 2018-11-14 04:40 UTC
I just released my game last Friday.  Overall it was smooth, but it looks like some (not all) of my users are getting JSON parsing exceptions in either the SignInSilentlyAsync or SignInAsync methods of the XboxLiveUser class.  These are first time users who have never signed into the game before.  Some have recovered over time, but others have continuously gotten the issue over the last few days.  I got one of them to send me a printout of the exception information:

![signinerror](https://user-images.githubusercontent.com/35792868/48460105-14786780-e782-11e8-9226-6e4c34ce0a43.png)

My calling code is:
         
`

         try
         {
             _errorString = string.Empty;
             var task = this._user.SignInSilentlyAsync(UIDispatcher).AsTask();
             task.Wait();
 
             if (task.Result.Status == SignInStatus.UserInteractionRequired)
             {
                 task = this._user.SignInAsync(UIDispatcher).AsTask();
                 task.Wait();
             }
 
             IsSignedIn = task.Result.Status == SignInStatus.Success;
 
             if (IsSignedIn)
             {
                 _xboxLiveContext = new Microsoft.Xbox.Services.XboxLiveContext(_user);
             }
             else
             {
                 GlobalLogic.Instance.LogError("Failed to sign in: " + task.Result.Status);
                 _errorString = "Sign In Failure: " + task.Result.Status;
                 IsSignedIn = false;
                 IsSigningIn = false;
                 return;
             }
         }
         catch (Exception ex)
         {
             GlobalLogic.Instance.LogError("Error signing in: " + ex);
             _errorString = "Sign In Exception: " + ex;
             IsSignedIn = false;
             IsSigningIn = false;
             return;
         }
`

This is inside a coroutine; I'm not using async/await because my project is still on .NET 3.5.  I'm using the 1804 Release of the Xbox Services UnityPackage.  I've tried using the 1807 Release but had to roll back because an exception at sign in was causing my app to fail cert.  My game is a Unity 5.6.4f UWP application.

Is this an issue inside the SignIn methods?  Do they try to parse some JSON?  Is there a workaround I can use to get my customers into the game?  Or is there a better way I can call the methods?  I'm going to try to wrap the SignInSilentlyAsync() method independently so if that's the one throwing the exception, it won't take down the other one, but other than that, I'm not sure what to do on my end.

Any ideas are welcome; if you need the gamertags of people experiencing this or more/all of my game code to investigate, I'd be happy to send you more information.  I've got one customer who is experiencing this threatening to sue me for his $2.99 back...so I'm trying to figure out a workaround as soon as possible.  :D

Thanks!
Mike Palotas

**Comment by Murtaya** [comment] 2018-11-14 05:09
I was also just able to get a single crash of the SIgnInAsync method.  However, I was able to sign in just by trying again.  That, along from the different stack trace (this time it's an invalid exception rather than a JSON parsing exception), makes me think this is different from the issue that the users are constantly/reliably seeing.  But if it helps, this is the error:

![mysigninerror](https://user-images.githubusercontent.com/35792868/48461312-f31a7a00-e787-11e8-9618-a4ae725513dc.png)

I created a bunch of test users and tried signing them in for the first time.  This happened on the third user (the first two signed in the first time with no issues).  This was also using my new code that wraps the initial, SignInSilentlyAsync method in its own try/catch:

`

        try
        {
            _errorString = string.Empty;

            bool silentSignInFailed = true;
            SignInStatus signInStatus = SignInStatus.UserCancel;
            try
            {
                var task = this._user.SignInSilentlyAsync(UIDispatcher).AsTask();
                task.Wait();

                signInStatus = task.Result.Status;
                silentSignInFailed = false;
            }
            catch (Exception ex)
            {
                // don't let the silent sign in attempt break the entire task.
                _errorString = "Silent Sign In Exception: " + ex;
            }

            if (silentSignInFailed || signInStatus == SignInStatus.UserInteractionRequired)
            {
                var task = this._user.SignInAsync(UIDispatcher).AsTask();
                task.Wait();
                signInStatus = task.Result.Status;
            }

            IsSignedIn = signInStatus == SignInStatus.Success;

            if (IsSignedIn)
            {
                _xboxLiveContext = new Microsoft.Xbox.Services.XboxLiveContext(_user);
            }
            else
            {
                GlobalLogic.Instance.LogError("Failed to sign in: " + signInStatus);
                _errorString += "Sign In Failure: " + signInStatus;
                IsSignedIn = false;
                IsSigningIn = false;
                return;
            }
        }
        catch (Exception ex)
        {
            GlobalLogic.Instance.LogError("Error signing in: " + ex);
            _errorString = "Interactive Sign In Exception: " + ex;
            IsSignedIn = false;
            IsSigningIn = false;
            return;
        }
`

**Comment by Murtaya** [comment] 2018-11-14 05:13
Have any other UWP games reported issues like this?  Are there known UWP games using the same library that I can download and try out?  Or example calling code?  I'm hoping that I'm just calling the library wrong (meaning I can fix it on my end)...

**Comment by XboxLiveForum** [comment] 2018-11-14 07:21
Thank you for contacting the helpdesk. Ticket 19620585 has been created per your request.

Thank you
Billy Egge
XDP Helpdesk

**Comment by michaelarts** [comment] 2019-02-28 14:32
Hello,

I am also getting users reporting issues with signing in. Because of this they are unable to play the game. Some users are able to sign in, while others are not. I suspect their issue is similar to this.

I would appreciate an update on this issue so I can pass an update along to my customers.

Michael

**Comment by michaelarts** [comment] 2019-02-28 14:38
@Murtaya were you able to find a solution to this issue? It's painful to see this happen to people because I see no way to fix it on my end.

**Comment by Murtaya** [comment] 2019-03-01 07:35
Unfortunately no.  My thread just got closed on xbox forums because ATG can't reproduce the issue:
https://forums.xboxlive.com/questions/85422/users-are-seeing-random-failures-at-sign-inany-kno.html?childToView=88015#comment-88015

I gave ATG the error messages and stack traces hoping they could at least find out where in the xbox code the issue might be coming from, but without a fiddler trace I guess they can't do anything.  I'm not able to get them a fiddler trace because it's not happening to me; I was lucky enough to just get the stace trace printout from a few very nice and understanding gamers who were running into this issue.

I'm not sure if it's happening to child accounts, or people in bad standing in Xbox Live, or whatever might be unique with these users, but yeah, it hurts to see these people pay money only to not be able to sign in (not to even mention the reviews I get because of this issue).

Is your game a UWP game?  I hate to say it, but maybe it's best for developers to not publish/develop games as UWP games.  Though I'm not sure if this is a UWP issue, a Unity issue, or what--it would have been nice for them to at least tell me that (and/or if they have other people seeing the same thing).  I don't see bad reviews on ERA games of people who can't log into them, which is why I'm wondering if this issue is UWP-specific.  I don't think being able to publish games on the PC alongside console is that important to me to have to deal with this--I should probably just make ERA games and just publish to console?

**Comment by michaelarts** [comment] 2019-03-01 13:08
Yes, my game is a UWP title using MonoGame. I agree that it seems like ERA is the better option at this point. Hopefully someone from Microsoft sees the new posts on this thread and can get something going here. I'm going to post my concerns in some other channels and see if we can bring some eyeballs to this issue.

**Comment by jasonsandlin** [comment] 2019-03-01 18:52
We're looking into the cause, but nothing to report at the moment.

**Comment by michaelarts** [comment] 2019-03-01 19:07
@jasonsandlin Thanks Jason! If it's of any use, I'd be happy to connect you with some of the users that are having issues. Maybe they can give more info about their account that can help you. Just let me know!

**Comment by Murtaya** [comment] 2020-06-01 05:08
@jasonsandlin, was there ever an update or fix released for this?  It seemed quiet for a while, but there are still a lot of 1-star reviews popping up on my game just because some people can't sign in.  I can't repro myself and it doesn't seem to happen everybody; there are plenty of good reviews coming in, so it's working for (hopefully) most of the people.

Or, is there anything at all I can do from my end to address this??  I'm hoping to release another game soon, but I'm afraid that this is going to be an issue on that one, too.  I'd be more than happy to give you guys my entire project/source code if that in any way helps...

I don't know what to tell these people :(
![image](https://user-images.githubusercontent.com/35792868/83377540-a22e9e80-a38a-11ea-8639-fa4943011e33.png)

**Comment by jasonsandlin** [comment] 2020-06-01 06:37
We tracked down one issue as I recall.  Ask them to go to Settings | System | About and report back which version of Windows 10 they are running.  For example, are they running Version = 1909, and OS Build = 18363.836?

**Comment by rakhad** [comment] 2020-09-24 00:27
Closing due to lack of updates.

**Closed by rakhad** 2020-09-24 00:27 UTC
