### ISSUE TITLE
MultiplayerManager's JoinLobby call may unexpectedly fail with HTTP_E_STATUS_FORBIDDEN (0x80190193).

### ISSUE THREAD

**Issue by bergerer** [Microsoft/xbox-live-api#351] opened 2018-04-24 00:08 UTC
Hello,

I'm seeing an unexpected HTTP_E_STATUS_FORBIDDEN when I use JoinLobby() to process an accepted invite. The steps to reproduce are:

1. Engage two users, A and B, on Xbox 1 where user A's XboxUserId compares less than B's XboxUserId.
2. Engage user C, who is not following user A, on Xbox 2.
3. Create a MPSD session containing user C with the "followed" joinRestriction.
4. Send an invite from user C to user B.
5. Accept the invite on machine 1.

In step 5 users A and B are passed to the JoinLobby() function along with the IProtocolActivatedEventArgs. It appears that things go wrong because the loop in multiplayer_lobby_client::commit_lobby_changes_helper() attempts to add the users to the MPSD session in the order that they appear when iterating the "xboxLiveContextMap" object. This is an std::map<> with the XboxUserId as the key type. Since A's XboxUserId compares less than B's the commit_lobby_changes_helper() function attempts to add user A to the MPSD session before user B (the invited user). This fails because user A does not have permission to write to the document.

The MPSD request returns status 403 and the following error message: 
>The requested session cannot be accessed. The calling user must have the multiplayer privilege and must be a member of the session if the session either isn't open or has a join restriction on it that the user doesn't satisfy, multi-user requests aren't allowed for large sessions, banned xuids can't access the session, users must have the communicate permission to access sessions that require it, users must qualify to access club sessions based on the club rules, and devices other than an Xbox One can only access sessions with user-style authorization.

I suspect that if the joinRestriction used in step #3 was "local" then it wouldn't matter whether user C is following user A, but I have not tested this.

I think the correct behaviour here would for MultiplayerManager to ensure that the user who was invited is added to the MPSD session first. This would enable the other local users on the invited user's machine to join as well. This is what happens when the invited user's XboxUserId, by chance, happens to compare lowest amongst the users attempting to join.

I also posted this bug [here](https://forums.xboxlive.com/questions/75492/) back on March 13th.

**Comment by XboxLiveForum** [comment] 2018-04-24 00:30
Hello, Bergerer.

I can see the issue is still investigating per engineering team
We will be closing this thread as the duplicate, for now, please check with "https://forums.xboxlive.com/questions/75492/index.html" for the further update of this issue.

Thanks for your patience.

Young

**Closed** 2018-04-24 00:46 UTC
